name: Deploy Admin & User Portals

on:
  push:
    branches:
      - main

jobs:
  deploy-admin:
    name: Deploy Admin Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy Admin to Vercel
        run: vercel --cwd frontend/adminPanel --prod --token ${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID_ADMIN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_ADMIN }}

  deploy-user:
    name: Deploy User Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy User to Vercel
        run: vercel --cwd frontend/userPanel --prod --token ${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID_USER }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_USER }}
